apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: httpd:2.4
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/local/apache2/conf/httpd.conf
        name: web-config
        subPath: httpd.conf
  volumes:
    - name: web-config
      configMap:
        name: httpd-conf
        items:
          - key: httpd.conf
            path: httpd.conf    
